// Generated by CoffeeScript 1.9.1
(function() {
  var http, requestListenerImpl, simpleServer;

  http = require('http');

  requestListenerImpl = function(serverRequest, serverResponse) {
    serverResponse.writeHead(200, {
      'content-type': 'text/plain'
    });
    serverResponse.write('Hello, Ilia!\n');
    return serverResponse.end();
  };

  simpleServer = http.createServer(requestListenerImpl);

  simpleServer.listen(8124);

  console.log('Server running on 8124');

}).call(this);

//# sourceMappingURL=simpleserver.js.map
